name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment:
      name: env
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test Model
      run: |
        python manage.py test websites.tests.test_model
    - name: Test View
      run: |
        python manage.py test websites.tests.test_view
    - name: Test Selenium
      run: |
        python manage.py test websites.tests.test_selenium
    - name: Test API
        python manage.py test websites.tests.test_apis
